services:
    experiments_app:
        container_name: esperiments_app
        build: 
            context: .
            dockerfile: Dockerfile
            target: final
        ports:
            - 8081:8081
            - 8082:8082
    unit-tests:
        container_name: unit-tests
        env_file: .env
        build:
          context: .
          dockerfile: Dockerfile
          target: unit-tests